# Generated by Django 3.2.2 on 2023-03-09 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoraUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=40)),
                ('interest', models.CharField(choices=[('ai', 'Artificial Intelligence'), ('w3', 'Web 3.0'), ('dsg', 'Design'), ('iv', 'Investment'), ('si', 'Self-Improvement')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('dora', models.DecimalField(decimal_places=10, max_digits=10)),
                ('status', models.CharField(choices=[('p', 'proceeding'), ('a', 'adopted')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert', to='apiapp.dorauser')),
                ('q_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_author', to='apiapp.dorauser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('c_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.dorauser')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('dora', models.DecimalField(decimal_places=10, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ar_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.dorauser')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('dora', models.DecimalField(decimal_places=10, max_digits=10)),
                ('status', models.CharField(choices=[('a', 'adopted'), ('r', 'rejected'), ('p', 'pending')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('an_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.dorauser')),
            ],
        ),
    ]
