# Generated by Django 3.2.2 on 2023-03-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='ar_author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='c_author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q_author',
        ),
        migrations.RemoveField(
            model_name='dorauser',
            name='wallet',
        ),
        migrations.AddField(
            model_name='dorauser',
            name='current_dora',
            field=models.DecimalField(decimal_places=10, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dorauser',
            name='interest',
            field=models.CharField(choices=[('ai', 'Artificial Intelligence'), ('w3', 'Web 3.0'), ('design', 'Design'), ('investment', 'Investment'), ('si', 'Self-Improvement')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.dorauser'),
        ),
        migrations.AddField(
            model_name='dorauser',
            name='walletAddress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='walletAddress', to='apiapp.wallet'),
        ),
    ]
