# Generated by Django 3.2.2 on 2023-03-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_auto_20230311_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='history',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
