# Generated by Django 3.2.2 on 2023-03-11 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_wallet_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dorauser',
            name='current_dora',
        ),
        migrations.AddField(
            model_name='dorauser',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dorauser',
            name='specialty',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dorauser',
            name='walletAddress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='walletAddress', to='apiapp.wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(),
        ),
    ]
