# Generated by Django 3.2.2 on 2023-03-11 08:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiapp', '0004_auto_20230311_0828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoraUser',
            new_name='PodoUser',
        ),
    ]
